### PR TITLE
Used a separate PropTypes package for React 16 and React 15 Compat

### PR DESCRIPTION
**Pull request by salmankhann**
Since the current source uses the PropTypes object from React which was discontinued in React 16, the current version of this library does not work with React 16.

I have separated the PropTypes package so that it works with Raect 16 as well as contains backward compatibility with React 15 adopters

### CODE REVIEW

**Comment by nijat13** [comment]
@salmankhann as [this PR](https://github.com/kuy/redux-tooltip/pull/66) already created, this PR doesn't have any power. Just use your branch in your app.

**Comment by salmankhann** [comment]
Not really, the other branch forces all  lib adopters to use react 16.*. My PR maintains backward compatibility with your existing user base.

Any reason why you’re hesitant to merge?

Sent from my iPhone

On Feb 12, 2018, at 4:50 PM, Nijat Ahmadov <notifications@github.com<mailto:notifications@github.com>> wrote:


@salmankhann<https://github.com/salmankhann> as this PR<https://github.com/kuy/redux-tooltip/pull/66> already created, this PR doesn't have any power. Just use your branch in your app.

**Comment by nijat13** [comment]
Actually, I'm not the repository owner and I can't merge anything.
I've created the PR as you did. The repo owner doesn't update anything, don't know why...

**Comment by salmankhann** [comment]
Got it. Anyhow for now I’m just using my fork in my project. Btw I suggest removing the 16.1.0 React dependency from your PR. There’s no reason to ask library adopters to use React 16 in order to use this library. That’s my opinion.

Sent from my iPhone

On Feb 13, 2018, at 5:57 PM, Nijat Ahmadov <notifications@github.com<mailto:notifications@github.com>> wrote:


Actually, I'm not the repository owner and I can't merge anything.
I've created the PR as you did. The repo owner doesn't update anything, don't know why...

**Comment by nijat13** [comment]
@salmankhann is there any way to update this repo without owner?
Or should we create new github repo and support?
Any suggestions?
This guy doesn't update the repo more than 10month...

**Comment by nijat13** [comment]
There's I've faced the styling issues as well.
Anyway, I've created [the repo](https://github.com/nijat13/reduxTooltip). Will develop here better product. You can contribute to build, will start tomorrow.

**Comment by Bradleykingz** [comment]
Fixed with c33168c

**Pull request closed without merging**
